DROP DATABASE IF EXISTS go;
CREATE DATABASE go;

DROP TABLE IF EXISTS MSDSCourse;
DROP TABLE IF EXISTS MSDSCourseCatalog;

\c go;

CREATE TABLE MSDSCourse (
    ID SERIAL,
    CID VARCHAR(100) PRIMARY KEY
);

CREATE TABLE MSDSCourseCatalog (
    CID VARCHAR(100),
    CNAME VARCHAR(100),
    CPREREQ VARCHAR(200)
);
