DROP DATABASE IF EXISTS MSDS;
CREATE DATABASE MSDS;

DROP TABLE IF EXISTS MSDSCourse;
DROP TABLE IF EXISTS MSDSCourseCatalog;

\c go;

CREATE TABLE MSDSCourseCatalog (
    ID SERIAL,
    CID VARCHAR(100) PRIMARY KEY
);

CREATE TABLE MSDSCourse (
    CID VARCHAR(100),
    CNAME VARCHAR(100),
    CPREREQ VARCHAR(200)
);
